# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_Name', models.CharField(max_length=500)),
                ('Description', models.CharField(max_length=500)),
                ('Version', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Asset_Name', models.CharField(max_length=500)),
                ('Operating_Sytem', models.CharField(max_length=200)),
                ('Version', models.CharField(max_length=200)),
            ],
        ),
    ]
