# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Type',
            field=models.CharField(default='Application', max_length=500),
        ),
        migrations.AddField(
            model_name='asset',
            name='Application',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='IACS_CSMS.Application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='Application_Name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='Description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='Version',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Asset_Name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Operating_Sytem',
            field=models.CharField(default='', max_length=200),
        ),
    ]
