# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0003_auto_20180228_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Zone_Type',
            field=models.CharField(choices=[('CS', 'Control System Zone'), ('SSZ', 'Safety System Zone'), ('PIZ', 'Plant Information Zone'), ('OZ', 'Other Zone'), ('IC', 'Internal Conduit'), ('EC', 'External Conduit')], default='CS', max_length=2),
        ),
    ]
