# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0004_asset_zone_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Type',
            field=models.CharField(choices=[('OS', 'Operating System'), ('App', 'Application'), ('Antivir', 'Anti Virus'), ('Util', 'Utility')], default='App', max_length=100),
        ),
    ]
