# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0005_auto_20180228_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='Application',
        ),
        migrations.AddField(
            model_name='asset',
            name='Application',
            field=models.ManyToManyField(default='', to='IACS_CSMS.Application'),
        ),
    ]
