# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0006_auto_20180228_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Asset_Type',
            field=models.CharField(choices=[('WS', 'Work Station'), ('SV', 'Server'), ('RT', 'Router'), ('PT', 'Printer')], default='WS', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Zone_Type',
            field=models.CharField(choices=[('CS', 'Control System Zone'), ('SSZ', 'Safety System Zone'), ('PIZ', 'Plant Information Zone'), ('OZ', 'Other Zone'), ('IC', 'Internal Conduit'), ('EC', 'External Conduit')], default='CS', max_length=50),
        ),
    ]
