# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0008_auto_20180228_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='Asset',
        ),
        migrations.AddField(
            model_name='zone',
            name='Asset',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='IACS_CSMS.Asset'),
        ),
    ]
