# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0009_auto_20180228_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='Asset',
        ),
        migrations.AddField(
            model_name='zone',
            name='Asset',
            field=models.ManyToManyField(default='', to='IACS_CSMS.Asset'),
        ),
    ]
