# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0011_remove_zone_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='Asset',
            field=models.ManyToManyField(to='IACS_CSMS.Asset'),
        ),
    ]
