# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0012_zone_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conduit',
            name='Conduit_Name',
        ),
        migrations.AddField(
            model_name='asset',
            name='Connect_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IACS_CSMS.Asset'),
        ),
        migrations.AddField(
            model_name='conduit',
            name='ConnectionPort',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conduit',
            name='ConnectionType',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='conduit',
            name='Protocol',
            field=models.CharField(choices=[('TCP/IP', 'TCP/IP'), ('MB', 'Modbus')], default='TCP/IP', max_length=10),
        ),
        migrations.AddField(
            model_name='conduit',
            name='Type',
            field=models.CharField(choices=[('IC', 'Internal Conduit'), ('EC', 'External Conduit')], default='IC', max_length=10),
        ),
        migrations.AddField(
            model_name='conduit',
            name='conduitName',
            field=models.CharField(default='', max_length=500),
        ),
    ]
