# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0013_auto_20180228_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conduit',
            name='ConnectionPort',
        ),
        migrations.RemoveField(
            model_name='conduit',
            name='ConnectionType',
        ),
        migrations.RemoveField(
            model_name='conduit',
            name='Protocol',
        ),
        migrations.RemoveField(
            model_name='conduit',
            name='Type',
        ),
        migrations.RemoveField(
            model_name='conduit',
            name='conduitName',
        ),
        migrations.AddField(
            model_name='conduit',
            name='Name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
