# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0014_auto_20180228_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conduit',
            name='Name',
        ),
    ]
