# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0015_remove_conduit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduit',
            name='Type',
            field=models.CharField(choices=[('IC', 'Internal Conduit'), ('EC', 'External Conduit')], default='IC', max_length=10),
        ),
    ]
