# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-28 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0018_auto_20180228_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='conduit',
            name='To_Zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='IACS_CSMS.Zone'),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='From_Zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='IACS_CSMS.Zone'),
        ),
    ]
