# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0020_auto_20180228_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='DeclaredUser',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 29, 51, 946142)),
        ),
        migrations.AddField(
            model_name='application',
            name='RevisedDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='asset',
            name='DeclaredUser',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='asset',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 29, 51, 947142)),
        ),
        migrations.AddField(
            model_name='asset',
            name='RevisedDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='conduit',
            name='DeclaredUser',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='conduit',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 29, 51, 950146)),
        ),
        migrations.AddField(
            model_name='conduit',
            name='RevisedDate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='zone',
            name='DeclaredUser',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='zone',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 29, 51, 949146)),
        ),
        migrations.AddField(
            model_name='zone',
            name='RevisedDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Asset_Type',
            field=models.CharField(choices=[('WS', 'Work Station'), ('SV', 'Server'), ('RT', 'Router'), ('PT', 'Printer'), ('OT', 'Other')], default='WS', max_length=50),
        ),
        migrations.AlterField(
            model_name='zone',
            name='Zone_Type',
            field=models.CharField(choices=[('BCPS', 'Basic Control Process System Zone'), ('SIS', 'Safety Instrumented Systems Zone'), ('PIZ', 'Plant Information Zone'), ('OZ', 'Other Zone'), ('CN', 'Corporate Network'), ('DMZ', 'DMZ Zone'), ('CCR', 'CCR Zone'), ('VPN', 'VPN Zone')], default='BCPS', max_length=50),
        ),
    ]
