# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0022_auto_20180301_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 33, 9, 871803)),
        ),
        migrations.AlterField(
            model_name='application',
            name='RevisedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 33, 9, 872805)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='RevisedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 33, 9, 876806)),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='RevisedDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 33, 9, 875806)),
        ),
        migrations.AlterField(
            model_name='zone',
            name='RevisedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
