# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 00:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0024_auto_20180301_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='RevisedDate',
        ),
        migrations.AlterField(
            model_name='application',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 34, 20, 737086)),
        ),
        migrations.AlterField(
            model_name='asset',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 34, 20, 738085)),
        ),
        migrations.AlterField(
            model_name='conduit',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 34, 20, 741088)),
        ),
        migrations.AlterField(
            model_name='zone',
            name='RegisteredDate',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 1, 0, 34, 20, 739088)),
        ),
    ]
