# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0033_auto_20180301_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='Description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
