# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 21:32
from __future__ import unicode_literals

import IACS_CSMS.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0034_auto_20180301_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='RegisteredDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='risk',
            name='Responsible_Person',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='risk',
            name='RevisedDate',
            field=models.DateTimeField(default=IACS_CSMS.models.one_day_hence, null=True),
        ),
    ]
