# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0038_auto_20180301_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='Asset',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='Zone', chained_model_field='Zone', horizontal=True, to='IACS_CSMS.Zone', verbose_name='Asset'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='Zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='IACS_CSMS.Zone'),
        ),
    ]
