# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 23:03
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0045_auto_20180301_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='Asset',
        ),
        migrations.AddField(
            model_name='risk',
            name='Asset',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='Zone_Name', chained_model_field='Zone_Name', default='', horizontal=True, to='IACS_CSMS.Asset', verbose_name='Asset'),
        ),
    ]
