# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 23:15
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0048_auto_20180301_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='Asset',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='Zone', chained_model_field='Zone', on_delete=django.db.models.deletion.CASCADE, to='IACS_CSMS.Asset'),
        ),
    ]
