# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-01 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0050_auto_20180301_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='Consequence',
            field=models.CharField(choices=[('CAT', 'Catastrophic - Multiple loss of life'), ('CRI', 'Catastrophic - Loss of a single life'), ('MAR', 'Major injuries to one or more persons'), ('NEG', 'Minor injuries at worst')], default='NEG', max_length=50),
        ),
        migrations.AlterField(
            model_name='risk',
            name='Likelihood',
            field=models.CharField(choices=[('FREQ', 'Frequent - Many times in system lifetime (Range > 10^-3)'), ('PRO', 'Probable - Several times in system lifetime'), ('OCC', 'Occasional - Once in system lifetime'), ('REM', 'Remote - Unlikely in system lifetime'), ('IMP', 'Improbable - Very unlikely to occur'), ('INC', 'Incredible - Cannot believe that it could occur')], default='FREQ', max_length=50),
        ),
    ]
