# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-02 12:54
from __future__ import unicode_literals

import IACS_CSMS.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0053_auto_20180302_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=500)),
                ('Counter_Type', models.CharField(choices=[('IR', 'Inherent Resilience'), ('AU', 'Authentication and Authorization Technologies'), ('AC', 'Filtering/Blocking/Access Control Technologies')], max_length=10, verbose_name='Counter Measure Category')),
                ('Description', models.CharField(default='', max_length=2000)),
                ('Responsible_Person', models.CharField(default='', max_length=200)),
                ('RegisteredDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('ReviewedDate', models.DateTimeField(default=IACS_CSMS.models.one_day_hence, null=True)),
                ('Risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IACS_CSMS.Risk')),
            ],
        ),
    ]
