# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0054_countermeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Application_Provider',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='Installed_User',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='Licensed',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='application',
            name='Location',
            field=models.URLField(default='', max_length=500),
        ),
    ]
