# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0055_auto_20180310_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Location',
        ),
        migrations.AddField(
            model_name='application',
            name='Storage_Location',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='Licensed',
            field=models.CharField(default='', max_length=50),
        ),
    ]
