# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0056_auto_20180312_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='Storage_Location',
            field=models.URLField(default='', max_length=100),
        ),
    ]
