# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0057_auto_20180312_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='Reviewed_User',
            field=models.CharField(default='', max_length=500),
        ),
    ]
