# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 18:09
from __future__ import unicode_literals

import IACS_CSMS.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IACS_CSMS', '0060_auto_20180312_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conduit',
            old_name='DeclaredUser',
            new_name='ResponsibleUser',
        ),
        migrations.RenameField(
            model_name='zone',
            old_name='DeclaredUser',
            new_name='ResponsibleUser',
        ),
        migrations.AddField(
            model_name='conduit',
            name='ReviewedDate',
            field=models.DateTimeField(default=IACS_CSMS.models.one_day_hence, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='ReviewedDate',
            field=models.DateTimeField(default=IACS_CSMS.models.one_day_hence, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ReviewedDate',
            field=models.DateTimeField(default=IACS_CSMS.models.one_day_hence, null=True),
        ),
    ]
